name: Scheduled Checkin

on:
  schedule:
    # Run Daily at 8:34 AM
    - cron: '34 8 * * *'

  # For running manually
  workflow_dispatch:
jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Python call
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install genshin
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install genshin[cookies,rsa]
    - name: Run code
      env:
        LT_UID: ${{ secrets.LT_UID }}
        LT_TOKEN: ${{ secrets.LT_TOKEN }}
        EMAIL_ADDR: ${{ secrets.EMAIL_ADDR}}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: python runCheckIn.py
